    <ul class="">
    <?php if ($this->customerHasAddresses()): ?>
        <li class="filed-width">
            <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
            <div class="input-box">
                <?php echo $this->getAddressesHtmlSelect('billing') ?>
            </div>
        </li>
        <?php $primaryBillingAddressId = $this->getCustomer()->getPrimaryBillingAddress()->getId(); ?>
        <script type="text/javascript">
        //<![CDATA[
            $('billing-address-select').observe('change', function(event){billing.setAddress($('billing-address-select').value);}.bind(this));
            billingSelect = $('billing-address-select');
            for(var i=0;i<billingSelect.length;i++) {
                if(billingSelect[i].value == <?php echo $primaryBillingAddressId ?>) {
                    billingSelect[i].selected = true;
                }
            }
        //]]
        </script>
    <?php endif; ?>
    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
        
            <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
            <ul class="step-wrapper">
                <li class="filed-width"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>
                <li class="filed-width">
                    <div class="field">
                        <label for="billing:telephone"><?php echo $this->__('Telephone') ?><em class="required">*</em></label>
                        <div class="input-box">
                            <input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" id="billing:telephone" />
                        </div>
                    </div>                    
                    <?php if(!$this->isCustomerLoggedIn()): ?>
                    <div class="field">
                        <label for="billing:email"><?php echo $this->__('Email Address') ?><em class="required">*</em></label>
                        <div class="input-box">
                            <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                        </div>
                    </div>
                    <?php endif ?>
                </li>
                <li class="filed-2-width">
                    <label for="billing:street1"><?php echo $this->__('Address') ?><em class="required">*</em></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry" />
                    </div>
                </li>
                <?php for ($i=2, $_n=$this->helper('customer/address')->getStreetLines(); $i<=$_n; $i++): ?>
                    <li class="filed-2-width" style="margin-top:4px;">
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address '.$i) ?>" name="billing[street][]" id="billing:street<?php echo $i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($i)) ?>" class="input-text" />
                        </div>
                    </li>
                <?php endfor ?>
                <li class="filed-2-width">
                    <label for="billing:country_id"><?php echo $this->__('Country') ?><em class="required">*</em></label>
                    <div class="input-box">
                        <?php echo $this->getCountryHtmlSelect('billing') ?>
                        <script type="text/javascript">
                            //<![CDATA[
                                <?php if($this->getQuote()->getBillingAddress()->getCountryId()): ?>
                                    billingCountry = $('billing:country_id');
                                    billingCountry[billingCountry.selectedIndex].removeAttribute('selected');
                                    for(var i=0; i<billingCountry.options.length; i++) {
                                        if(billingCountry[i].value == '<?php echo $this->getQuote()->getBillingAddress()->getCountryId(); ?>') {
                                            billingCountry[i].setAttribute('selected', true);
                                        }
                                    }
                                    <?php endif; ?>
                                $('billing:country_id').observe('change', function(event){billing.saveCountry();Event.stop(event);}.bind(this));
                            //]]
                        </script>
                    </div>
                </li>
                <li class="filed-2-width">
                    <label for="billing:city"><?php echo $this->__('City') ?><em class="required">*</em></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text required-entry" id="billing:city" />
                    </div>
                </li>
                <li class="filed-width">
                    <div class="field">
                        <label for="billing:postcode"><?php echo $this->__('Zip/Postal Code') ?><em class="required">*</em></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="postcode input-text validate-zip-international required-entry" />
                            <script type="text/javascript">
                                //<![CDATA[
                                    $('billing:postcode').observe('change', function(event){billing.saveCountry();Event.stop(event);}.bind(this));
                                //]]
                            </script>
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:region_id"><?php echo $this->__('State/Province') ?><em class="required">*</em></label>
                        <div class="input-box">
                            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="region validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                $('billing:region_id').observe('change', function(event){billing.saveCountry();Event.stop(event);}.bind(this));
                            //]]>
                            </script>
                            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="region input-text" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="filed-width">

                    <div class="field">
                        <label for="billing:company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:fax"><?php echo $this->__('Fax') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text" id="billing:fax" />
                        </div>
                    </div>
                </li>
                <?php if(!$this->isCustomerLoggedIn()): ?>

                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                    <?php if (($_dob&&$_dob->isEnabled()) || ($_gender&&$_gender->isEnabled())): ?>
                <li class="filed-width">
                    <?php if ($_dob->isEnabled()): ?>
                    <div class="filed-width">
                        <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())
                        ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                    </div>
                    <?php endif; ?>
                    <?php if ($_gender->isEnabled()): ?>
                    <div class="filed-width">
                        <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())
                        ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                    </div>
                    <?php endif; ?>
                </li>
                <?php endif ?>

                <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                <?php if ($_taxvat->isEnabled()): ?>
                <li>
                    <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                </li>
                <?php endif ?>
                    <?php $reg=Mage::helper('onecheckout')->getConfig('general/enable_register');
                    if($reg>0): ?>
                       <li class="filed-2-width">
                           <input type="hidden" name="billing[register]" 
                               value="<?php $reg; ?> "   
                               title="<?php echo $this->__('Create an account') ?>" 
                               id="billing:register" 
                               class="checkbox" 
                               />
                           <label for="billing:register"><?php echo $this->__('Create an account') ?></label>
                       </li>
                       <li class="filed-width" id="register-customer-password" style="<?php if($reg==1){echo "display:block;";}else{echo "display:none;";} ?>">
                            <div class="field">
                               <label for="billing:customer_password"><?php echo $this->__('Password') ?><em class="required">*</em></label>
                               <div class="input-box">
                                   <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                               </div>
                           </div>
                            <div class="field">
                               <label for="billing:confirm_password"><?php echo $this->__('Re-Enter') ?><em class="required">*</em></label>
                               <div class="input-box">
                                   <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                               </div>
                           </div>
                       </li>
                    <?php endif; ?>
                <?php endif; ?>
                       
                       
                       
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <li class="filed-2-width">
                        <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                    </li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                <?php endif; ?>
                    
                    
                <?php $checkUseForShipping = 0; ?>    
                <?php if ($this->canShip()): ?>
                    <li class="filed-2-width">
                        <br class="clear"/>
                        <?php $checkUseForShipping = Mage::getSingleton('checkout/session')->getData('use_for_shipping'); ?>
                        <input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" <?php if($checkUseForShipping): ?>checked="checked"<?php endif; ?> value="1" title="<?php echo $this->__('Ship to different address') ?>" class="checkbox" /><label for="billing:use_for_shipping_yes"><?php echo $this->__('Ship to different address') ?></label>
                        <script type="text/javascript">
                            //<![CDATA[
                                $('billing:use_for_shipping_yes').observe('click', function(event){billing.enalbleShippingAddress();}.bind(this));
                            //]]
                        </script>
                    </li>
                <?php endif; ?>                    
            </ul>
    </li>
    </ul>
    

<script type="text/javascript">
//<![CDATA[
    var billing = new Billing(
                    '<?php echo !$checkUseForShipping; ?>',
                    '<?php echo $this->getUrl('checkout/go/saveBilling'); ?>',
                    '<?php echo $this->getUrl('checkout/go/switchMethod'); ?>',
                    '<?php echo $this->getUrl('checkout/go/getAddress') ?>address/'
                );
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');
//]]>
</script>

<br class="clear"/>