
<div id="osc-coupon-form">
    <div id="osc-coupon-form-div">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="coupon_form" method="post">
            <div class="extra-buttons">
                <input type="hidden" name="remove" id="remove-coupone" value="0" />
                <div class="coupon-field">
                    <input class="input-text"  id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
                </div>
                <input type="button" id="apply_coupon" class="left coup_button green"  
                       onclick="coupon.coupon(false)" value="<?php echo $this->__('Apply Coupon'); ?>" 
                       title="<?php echo $this->__('Apply Coupon'); ?>" />
                <input type="button" id="remove_coupon" class="coup_button grey" style="<?php if(!strlen($this->getCouponCode())){echo "display:none";}?>" onclick="coupon.coupon(true)" value="<?php echo $this->__('Cancel Coupon'); ?>" title="<?php echo $this->__('Cancel Coupon'); ?>"/>
            </div>
        </form>
    </div>
    <div id="osc-coupon-message" class="osc-error-message"></div>
</div>



<script type="text/javascript">
    //<![CDATA[
        var coupon = new Coupon('<?php echo $this->getUrl('checkout/go/couponPost') ?>');
    //]]>
    
</script>
